FROM node:20.19.2 AS node
RUN apt-get update -qq

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# 本番環境
FROM nginx:1.25 as prod
COPY --from=node /app/dist /var/www/html

COPY nginx.conf /etc/nginx/
COPY default.conf.template /etc/nginx/templates/

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]