services:
  backend:
    container_name: lesson_booking_backend
    build: 
      context: ./backend
      dockerfile: Dockerfile.php.dev
    extra_hosts:
     - "host.docker.internal:host-gateway"
    volumes:
     - ./backend/:/var/www/
     - ./backend/storage/app:/var/www/storage/app/
     - ./backend/public:/var/www/public
    networks:
      - lesson-booking-network
  frontend:
    container_name: lesson_booking_frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile.vite.dev
    ports:
      - "3000:3000"
    command: "npm run dev"
    volumes:
      - ./frontend/:/var/www/
      - /var/www/node_modules
    networks:
      - lesson-booking-network
  nginx:
    container_name: lesson_booking_nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile.nginx.prod
    ports:
      - "80:80"
      - "9000:9000"
      - "5173:5173"
    volumes:
      - ./backend/:/var/www/
      - ./backend/storage/app:/var/www/storage/app/
      - ./backend/public:/var/www/public
    depends_on:
      - frontend
      - backend
    networks:
      - lesson-booking-network
networks:
  lesson-booking-network:
    external: true
