services:
  backend:
    container_name: lesson_booking_backend
    build: 
      context: ./backend
      dockerfile: Dockerfile.prd
    extra_hosts:
     - "host.docker.internal:host-gateway"
    user: "root"
    command: sh -c "mkdir -p /var/www/storage/logs && chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache && chmod -R ug+rwX /var/www/storage /var/www/bootstrap/cache && php-fpm"
    volumes:
     - ./backend/storage/app:/var/www/storage/app/
     - ./backend/storage/logs:/var/www/storage/logs/
     - ./backend/public:/var/www/public
    networks:
      - lesson-booking-network
  frontend:
    container_name: lesson_booking_frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prd
    ports:
      - "3000:3000"
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    command: sh -c "npm run build && npm run preview -- --host 0.0.0.0 --port 3000"
    volumes:
      - ./frontend/:/var/www/
      - /var/www/node_modules
    networks:
      - lesson-booking-network
  nginx:
    container_name: lesson_booking_nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile.nginx.prd
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
      - "5173:5173"
    volumes:
      - ./backend/storage/app:/var/www/storage/app/
      - ./backend/storage/app/public:/var/www/public/storage
      - ./backend/public:/var/www/public
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - frontend
      - backend
    networks:
      - lesson-booking-network
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - lesson-booking-network
  certbot-renew:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: sh -c "while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h; done"
    networks:
      - lesson-booking-network
networks:
  lesson-booking-network:
    external: true
