<?php

namespace App\Models;

class Order extends AbstractModel
{
    protected $table = 't_order';
    protected $primaryKey = ['order_date', 'inquiry_no'];
    public $incrementing = false;

    const CREATED_AT = 'cmn_create_date';
    const UPDATED_AT = 'cmn_update_date';

    protected $fillable = [
        'order_date',
        'inquiry_no',
        'order_status',
        'temporary_flg',
        'rapid_code',
        'root_code',
        'order_start_datetime',
        'order_end_datetime',
        'order_create_div',
        'plan_receive_datetime',
        'plan_receive_require_time',
        'plan_receive_time_span',
        'plan_send_datetime',
        'plan_send_require_time',
        'plan_send_time_span',
        'bill_div',
        'local_payment_div',
        'slip_div',
        'product_div',
        'round_trip_div',
        'security_div',
        'security_quantity',
        'errand_flg',
        'reserve_flg',
        'reserve_receive_datetime',
        'reserve_send_datetime',
        'ahead_receive_days',
        'ahead_send_datetime',
        'charter_flg',
        'charter_start_datetime',
        'charter_end_datetime',
        'envoy_flg',
        'luggage_weight_size',
        'luggage_num',
        'luggage_info',
        'delivery_div',
        'note',
        'total_distance',
        'delivery_amount',
        'outside_amount',
        'extra_discount_amount',
        'extra_discount_rate',
        'reserve_amount',
        'reserve_cnt',
        'agency_amount',
        'drop_in_amount',
        'drop_in_cnt',
        'ahead_receive_amount',
        'charter_amount',
        'charter_time',
        'security_amount',
        'wait_amount',
        'wait_time',
        'over_time_amount',
        'over_time',
        'over_distance_amount',
        'over_distance',
        'cancel_flg',
        'cancel_amount',
        'express_amount',
        'others_amount',
        'subtotal',
        'consumption_tax',
        'total1',
        'advance_amount',
        'advance_amount_items',
        'total2',
        'grand_total',
        'order_change_history',
        'special_delivery_flg',
        'cmn_create_function_id',
        'cmn_create_user_id',
        'cmn_create_date',
        'cmn_update_function_id',
        'cmn_update_user_id',
        'cmn_update_date',
    ];
}