FROM php:8.2-fpm

# Installing middlewares
RUN apt-get update \
&& apt-get install -y \
git \
zip \
unzip \
vim \
libpng-dev \
libpq-dev \
&& docker-php-ext-install pdo_pgsql pgsql

# Insalling Composer
RUN cd /usr/bin && curl -s http://getcomposer.org/installer | php -- --version=2.6.5 && ln -s /usr/bin/composer.phar /usr/bin/composer

WORKDIR  /var/www

COPY . .
COPY composer.json /var/www
COPY composer.lock /var/www
COPY php.ini /usr/local/etc/php/
COPY www.conf /usr/local/etc/php-fpm.d/zzz-www.conf

RUN composer install

RUN chmod 777 -R /var/www
# RUN chmod 777 -R /tmp/xdebug-file.log

# Installing Xdebug
RUN pecl install xdebug \
    && docker-php-ext-enable xdebug
